### Recuperar las peliculas
GET http://localhost:2712/movies

### Por id
GET http://localhost:2712/movies/4b51b589-71fe-11f1-86e9-a0ad9f862f68
### Por genero
GET http://localhost:2712/movies?genre=DRAMA

### Crear una peli
POST http://localhost:2712/movies
Content-Type: application/json

{
   "title":"Piratas del Caribe 1",
   "year":2008,
   "director":"Gore Jackson",
   "duration":186,
   "poster":"https://i.ebayimg.com/images/g/0hoAAOSwe7peaMLW/s-l1600.jpg",
   "genre":[
      "Action",
      "Adventure",
      "Drama"
   ],
   "rate":9.2
}

### Actualizar una peli
PATCH http://localhost:2712/movies/1544793a-7445-11f1-86e9-a0ad9f862f68
Content-Type: application/json

{
    "director": "Gore Verbinski",
    "year": 2010
}

### borrar pelicula
DELETE http://localhost:2712/movies/03cd4f28-7372-11f1-86e9-a0ad9f862f68