### Recuperar las peliculas
GET http://localhost:2712/movies

### Por id
GET http://localhost:2712/movies/21272801-7121-11f1-86e9-a0ad9f862f68

### Por genero
GET http://localhost:2712/movies?genre=DRAMA

### Crear una peli
POST http://localhost:2712/movies
Content-Type: application/json

{
    "title": "Piratas del Caribe 3",
    "year": 2008,
    "director": "Gore Jackson",
    "duration": 186,
    "poster": "https://i.ebayimg.com/images/g/0hoAAOSwe7peaMLW/s-l1600.jpg",
    "genre": [
      "Action",
      "Adventure",
      "Drama"
    ],
    "rate": 10
}

### Actualizar una peli
PATCH http://localhost:2712/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "director": "Gore Verbinski",
    "year": 2008
}

### borrar pelicula
delete http://localhost:2712/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf